version: "3.8"

services:
  node-red:
    container_name: node-red-wsp
    build: .
    ports:
      - "1880:1880"
    volumes:
      - ./data:/usr/src/app/data      # Carpeta persistente en Windows
      - ./flows:/usr/src/app/flows    # Almacén de flujos de Node-RED
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048  # Optimiza el rendimiento de Node.js
    restart: unless-stopped